language: python

addons:
    postgresql

services:
    - postgresql

script:
    - python -m pytest -v

deploy:
    provider: heroku
    api_key: b4f5121d-c2d8-4c4d-b9ad-67fd70853136
    app: hello-world-print
    on:
        repo: devel-test/hello_world_print

