language: python

addons:
    postgresql

services:
    - postgresql

before_script:
    - psql --version
    - psql -c "create database hello_world_db;" -U postgres
    - psql -d hello_world_db -c "create table words(id INT, text VARCHAR);" -U postgres
    - psql -d hello_world_db -c "insert into words values(1, 'world');" -U postgres

script:
    - python -m pytest -v

deploy:
    provider: heroku
    api_key: b4f5121d-c2d8-4c4d-b9ad-67fd70853136
    app: hello-world-print
    on:
        repo: devel-test/hello_world_print

